version: '2.14.0'

services:
  social-media:
    image: 'wso2/social-media:0.0.1'
    ports:
      - '9090:9090'
    links:
      - sentiment-analysis
      - sts
      - mysql
      - nats
    depends_on: 
      sentiment-analysis: 
          condition: service_started
      sts: 
          condition: service_started
      mysql: 
          condition: service_healthy
      nats: 
          condition: service_started
    network_mode: "host"

  slack-message-sender:
    image: 'wso2/slack-message-sender:0.0.1'
    links:
      - nats
    depends_on: 
      nats: 
          condition: service_started

  sentiment-analysis:
    image: 'wso2/sentiment-api-secured:0.0.1'
    ports:
      - '9098:9098'

  sts:
    image: 'wso2/sts-service:0.0.1'
    ports:
      - '9445:9445'

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=social_media_database
      - MYSQL_USER=social_media_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"
