### Creat a user
POST http://localhost:9090/social-media/users
content-type: application/json

{
    "birthDate": {
        "year": 1987,
        "month": 02,
        "day": 06
    },
    "name": "Rimas",
    "mobileNumber": "+94718923456"
}

HTTP/1.1 405  - Method Not Allowed
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 17:16:38 +0530
content-encoding: gzip
content-length: 157
###
GET http://localhost:9090/social-media/users

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 17:16:39 +0530
content-encoding: gzip
content-length: 118
###
GET http://localhost:9090/social-media/users/2

HTTP/1.1 404  - Not Found
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 18:34:01 +0530
content-encoding: gzip
content-length: 135
###
GET http://localhost:9090/social-media/users/3/posts

HTTP/1.1 404  - Not Found
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 17:16:40 +0530
content-encoding: gzip
content-length: 183
###
POST http://localhost:9090/social-media/users/3/posts
content-type: application/json

{
    "description": "I want to learn Azure",
    "tags": "azure,cloud,devops",
    "category": "education"
}

HTTP/1.1 404  - Not Found
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 17:16:40 +0530
content-encoding: gzip
content-length: 186
###
DELETE http://localhost:9090/social-media/users/1

HTTP/1.1 404  - Not Found
content-type: application/json
connection: close
server: ballerina
date: Sat, 9 Aug 2025 17:16:40 +0530
content-encoding: gzip
content-length: 183
###
POST http://localhost:9099/text-processing/api/sentiment

{
    "text": "I love this product"
}